### ISSUE TITLE
【请教】如何分页显示？

### ISSUE THREAD

**Issue by BI7PRK** [yeszao/FastPHP#10]
刚刚学PHP。请指教，数据读取如何分页显示？
谢谢。

**Comment by adileli** [comment]
原理是这样 URL有个page参数，比如`blog.com/doc/detail/1?page=2`
然后控制器接收到page参数，处理一下page，再传到modal
modal再把相应的数据返回到控制器
控制器渲染到页面

实现例子之一
控制器接受page 并处理成2个参数，$start和$limit
比如一页显示20条记录，那么第一页`$start=0 $limit=20`，第二页`$start=20 $limit=40`
tips:可以写个Page类处理这个事情。
modal的search方法接受这个两个参数，修改sql语句为 `LIMIT = $start,$limit`
大概逻辑是这样
